# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class EcsConnect < Formula
  desc "Interactive CLI for exec-ing into running AWS ECS tasks"
  homepage "https://github.com/vipinvkartha/ecs-connect"
  version "0.1.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/vipinvkartha/ecs-connect/releases/download/v0.1.1/ecs-connect_darwin_amd64.tar.gz"
      sha256 "2796acfa17248ee3f02e898e610d1f8c259190148e08f1d146440c10154a6951"

      define_method(:install) do
        bin.install "ecs-connect"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/vipinvkartha/ecs-connect/releases/download/v0.1.1/ecs-connect_darwin_arm64.tar.gz"
      sha256 "84852a6a18fb1564a7c9d57f06db231cf18ba49bb8a6f8827d6e8161b99e2bce"

      define_method(:install) do
        bin.install "ecs-connect"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/vipinvkartha/ecs-connect/releases/download/v0.1.1/ecs-connect_linux_amd64.tar.gz"
      sha256 "54c0dab49f1253552d3e0a8cf1143784d72935ddb39e1259cc77dfda63b2ff4e"
      define_method(:install) do
        bin.install "ecs-connect"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/vipinvkartha/ecs-connect/releases/download/v0.1.1/ecs-connect_linux_arm64.tar.gz"
      sha256 "888bda340f25913090529b53c68c1538df708a3247bc62948a071fa7c4aadb44"
      define_method(:install) do
        bin.install "ecs-connect"
      end
    end
  end

  def caveats
    <<~EOS
      You need AWS CLI, session-manager-plugin, and ECS Exec enabled on target services.
      Config is read from ./.ecs-connect.yaml, ~/.ecs-connect.yaml, or --config.
    EOS
  end

  test do
    system "#{bin}/ecs-connect", "--help"
  end
end
