# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class EcsConnect < Formula
  desc "Interactive CLI for exec-ing into running AWS ECS tasks"
  homepage "https://github.com/vipinvkartha/ecs-connect"
  version "0.1.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/vipinvkartha/ecs-connect/releases/download/v0.1.2/ecs-connect_darwin_amd64.tar.gz"
      sha256 "954781519f0b0a60ee0357da72213a8900ecee54dfc63765ab49e1446e29d48b"

      define_method(:install) do
        bin.install "ecs-connect"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/vipinvkartha/ecs-connect/releases/download/v0.1.2/ecs-connect_darwin_arm64.tar.gz"
      sha256 "362888c9b5519e926501ac9de4b883c9691e37795414ad3731440f62b3999ed4"

      define_method(:install) do
        bin.install "ecs-connect"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/vipinvkartha/ecs-connect/releases/download/v0.1.2/ecs-connect_linux_amd64.tar.gz"
      sha256 "ba54a31933310d2c5770c4028006a3a598c8d594334475a253dfedc93247b517"
      define_method(:install) do
        bin.install "ecs-connect"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/vipinvkartha/ecs-connect/releases/download/v0.1.2/ecs-connect_linux_arm64.tar.gz"
      sha256 "49e05d68345807cea4dac585c3346164a22a86a04d5933e8a24b60d60c8c5e54"
      define_method(:install) do
        bin.install "ecs-connect"
      end
    end
  end

  def caveats
    <<~EOS
      You need AWS CLI, session-manager-plugin, and ECS Exec enabled on target services.
      Config is read from ./.ecs-connect.yaml, ~/.ecs-connect.yaml, or --config.
    EOS
  end

  test do
    system "#{bin}/ecs-connect", "--help"
  end
end
